[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "
[cmd_duration]
min_time = 500
format = " [$duration](bold yellow)"
[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false
show_always = true
[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"
